### ISSUE TITLE
Issue with predefined argument for lodestar, CL participant throwing unknown arguments error.

### ISSUE THREAD

**Issue by himanshu-bq** [kurtosis-tech/eth2-merge-kurtosis-module#126]
While running that kutosis command facing some unknown arguments error which are mentioned below. 

**Command : -** 

**`kurtosis module exec --enclave-id eth2 kurtosistech/eth2-merge-kurtosis-module --execute-params "$(cat ~/eth2-module-params.yaml)"`**

**Error**

**` ✖ Unknown arguments: rootDir, network.discv5.enabled, eth1.enabled, api.rest.enabled, api.rest.host, api.rest.api, api.rest.port, network.subscribeAllSubnets, metrics.enabled, metrics.listenAddr, metrics.serverPort`**

**Explanation : -**

With following participant in **eth2-module-params.yaml** file:

```
elType: "geth"
elImage: "ethereum/client-go:latest"
clType: "lodestar"
clImage: "lodestar: chainsafe/lodestar:next"
```

Seems loadstar use different arguments then kurtosis, as in the Chainsafe Lodestar documentation lodestar uses root data directory as `--dataDir` option whereas kurtosis uses [`--rootDir`](https://github.com/kurtosis-tech/eth2-merge-kurtosis-module/blob/7fafd166d46654c652fb8c1477c1898c6d6c8c76/kurtosis-module/impl/participant_network/cl/lodestar/lodestar_launcher.go#L179) option for root directory for lodestar.

Reference : -

- [Lodestar options](https://chainsafe.github.io/lodestar/reference/cli/)

**Comment by mieubrisse** [comment]
Hey @himanshu-bq did you find the solution to your problem? I believe the issue is that the clImage is `lodestar: chainsafe/lodestar:next` when it should be `chainsafe/lodestar:next`
