### ISSUE TITLE
Set `netrestrict` in Geth to reduce peering to only those clients from inside the network

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/eth2-merge-kurtosis-module#68]
This would be:
1. Setting the `netrestrict` (?) flag in the Geth launcher
2. Verifying that the public ports (the host machine ports that show up on `enclave inspect`) still work properly (because that traffic would technically come from outside the network)

References:
 * https://discord.com/channels/783719264308953108/933134266580234290/946870392700694618
 * https://discord.com/channels/783719264308953108/933134266580234290/947165452633772072

**Comment by z3n-chada** [comment]
thanks for adding the issue. For my uses I just use the docker network ip subnet, I assume that is something you are able to fetch from launchers.
