### ISSUE TITLE
Nimbus fails to start due to JWT error

### ISSUE THREAD

**Issue by marioevz** [kurtosis-tech/eth2-merge-kurtosis-module#81]
Nimbus CL client currently fails in develop branch with the following error:
`FAT 2022-03-23 04:01:01.109+00:00 Specified a JWT secret file which couldn't be loaded topics="beacnde" err="no 0x-prefixed hex string found"`

The combination is Geth+Nimbus for the testnet where the issue was hit:
```
{
    "participants": [
        {
            "elType": "geth",
            "clType": "nimbus"
        },
        {
            "elType": "geth",
            "clType": "nimbus"
        },
        {
            "elType": "geth",
            "clType": "nimbus"
        }
    ],
    "network": {
        "totalTerminalDifficulty": 50000000,
        "mergeForkEpoch": 3
    },

    "logLevel": "info"
}
```

**Comment by mieubrisse** [comment]
Hey @marioevz ! Could you run a `kurtosis enclave dump` on the enclave with the problem and send me the ZIP? (feel free to send me it on Discord; I've added you as a friend)
